apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "workload-variant-autoscaler.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "workload-variant-autoscaler.labels" . | nindent 4 }}
imagePullSecrets:
  - name: {{ .Values.wva.imagePullSecret | default "" }}
