{{- if .Values.controller.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "workload-variant-autoscaler.fullname" . }}-controller-manager-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "workload-variant-autoscaler.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ include "workload-variant-autoscaler.fullname" . }}-controller-manager
type: kubernetes.io/service-account-token
{{- end }}
