{{- if .Values.controller.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "workload-variant-autoscaler.fullname" . }}-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "workload-variant-autoscaler.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "workload-variant-autoscaler.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "workload-variant-autoscaler.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
{{- end }}
