{{- if .Values.controller.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "workload-variant-autoscaler.clusterResourceName" . }}-manager-rolebinding
  labels:
    {{- include "workload-variant-autoscaler.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "workload-variant-autoscaler.clusterResourceName" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "workload-variant-autoscaler.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
{{- end }}
